### ISSUE TITLE
Separate into core, frontend, and backend engines (like Solidus)

### ISSUE THREAD

**Issue by masonjeffreys** [boomerdigital/solidus_flexi_variants#2]
I have been modifying a fork of this gem to separate the solidus_flexi_variants gem into core, frontend, and backend engines. It's a similar format to the solidus path. I went down this path because I wanted to use the models, business logic, and admin views but not the frontend stuff.

In fact, if a person isn't using solidus_frontend, they may not be able to get the existing solidus_flexi_variants gem to work because it depends on standard solidus/spree frontend controllers.

Are you interested in a pull request for this separation? I'll probably need some help to finish it.

**Comment by dhonig** [comment]
Its probably a good idea.  Can you outline the changes?

**Comment by masonjeffreys** [comment]
I'll give it a shot:

- [ ] Create engines inside top level for core, frontend (consumer-facing), and backend (admin) gems
- [ ] Top level gemspec file will require CORE, BACKEND, and FRONTEND
- [ ] CORE, BACKEND, and FRONTEND gemspec files should be edited so that CORE requires nothing, BACKEND requires CORE, and FRONTEND requires CORE
Separate existing code by functionality
- [ ] Migrations, models, decorators, spec and other code that references or expands solidus_core files should end up in CORE
- [ ] Controllers, views, helpers, routes, and spec that references or expands solidus_backend or other admin tasks should end up in BACKEND
- [ ] Controllers, views, helpers, routes and spec that references or expands solidus_frontend should end up in FRONTEND
- [ ] Gemspec dependencies should be evaluated such that only gems required for each engine are in the gemspec
- [ ] Generator for each gem should be made independent
- [ ] Each gem should be released such that it can be used independently
- [ ] Test suite for each gem should be verified
- [ ] Test suite for each gem should be expanded

**Comment by masonjeffreys** [comment]
Closing due to lack of movement. Probably too big of a change without motivation to justify it. Pursuing alternative method of allowing users without solidus frontend to still use this gem.
