### ISSUE TITLE
Getting tests working

### ISSUE THREAD

**Issue by jeremygpeterson** [boomerdigital/solidus_flexi_variants#5]
I'm having trouble getting tests to pass for this project.  There were a few issues with FactoryBot and JavaScript Assets. My branch is located at: https://github.com/jeremygpeterson/solidus_flexi_variants

The branch has updates for:
* upgrade FactoryGirl to FactoryBot
* add rails_jquery to solidus_flexi_variants.gemspec
* add jquery.validate.min.js to vendor/assets/javascripts/jquery.validate/

Steps to reproduce test:
* `rake test_app`
* `rake`

Failed Tasks:
rspec ./spec/models/spree/order_contents_decorator_spec.rb:36
rspec ./spec/models/spree/order_contents_decorator_spec.rb:40
rspec ./spec/features/admin/ad_hoc_option_plus_exclusions_spec.rb:13
rspec ./spec/features/admin/ad_hoc_option_plus_exclusions_spec.rb:78
rspec ./spec/features/admin/product_customizations_spec.rb:22
rspec ./spec/features/product_page_ad_hoc_opts_and_exclusions_feature_spec.rb:20
rspec ./spec/features/product_page_ad_hoc_opts_and_exclusions_feature_spec.rb:47
rspec ./spec/features/product_page_ad_hoc_opts_and_exclusions_feature_spec.rb:41

**Comment by masonjeffreys** [comment]
Hi Jeremy,
I ran into some of the same issues as you and performed similar fixes (except that I didn't add rails_jquery gem).
Did all the tests pass after you made the changes noted above?
Thanks,
Jeff

**Comment by jeremygpeterson** [comment]
Hi Jeff,

These are the failed tests after the changes I made.  I added changes to resolve missing jquery and jquery.validate, that were failing in tests.

**Comment by acreilly** [comment]
Issue resolved with #10
